language: python
matrix:
  include:
  - name: "Plone Tests"
    python: 2.7.14
    env: TEST_SUITE=plone
  - name: "Guillotina Tests"
    python: 3.7
    env: TEST_SUITE=guillotina
cache:
  pip: true
  directories:
   - node_modules
sudo: required
services:
  - docker
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
- if [ "$TEST_SUITE" == "guillotina" ]; then
  echo "Guillotina Before Install"
  docker build -t plone/plone-react:$TRAVIS_BRANCH .
  fi
- if [ "$TEST_SUITE" == "plone" ]; then
  echo "Guillotina Before Install"
  nvm install 8.11.3
  mkdir webdriver
  wget https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-linux64.tar.gz
  tar -xzf geckodriver-v0.20.0-linux64.tar.gz -C webdriver
  wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
  unzip chromedriver_linux64.zip -d webdriver
  export PATH=$PATH:$(pwd)/webdriver
  fi
install:
- if [ "$TEST_SUITE" == "plone" ]; then
  virtualenv env --python=$(which python) --no-site-packages
  env/bin/pip install zc.recipe.egg==2.0.4 --no-cache-dir
  env/bin/pip install -r api/docker/requirements.txt
  env/bin/pip install -U https://github.com/zopefoundation/z3c.autoinclude/archive/pip.tar.gz#egg=z3c.autoinclude
  fi
- if [ "$TEST_SUITE" == "guillotina" ]; then
  echo "Guillotina CMS Install"
  fi
- yarn
- yarn build
script:
- yarn coverage
- if [ "$TEST_SUITE" == "plone" ]; then
  PYTHONPATH=$(pwd)/tests env/bin/pybot -v BROWSER:headlesschrome tests
  fi
- if [ "$TEST_SUITE" == "guillotina" ]; then
  PYTHONPATH=$(pwd)/tests env/bin/pybot -v BROWSER:headlesschrome tests_guillotina
  fi
after_success:
- if [ "$TEST_SUITE" == "guillotina" ]; then
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  docker push plone/plone-react:$TRAVIS_BRANCH
  fi
