site_name: Volto documentation
theme:
  name: "material"
nav:
  - Introduction: "01-installing"
  - Semantic UI: "02-semantic-ui"
  - Theming: "03-theming"
  - Deploying: "04-deploying"
  - Developer Guidelines: "05-developer-guidelines"
  - Contributing: "06-contributing"
